const CONSTANT = {

    //BASE_URL:'https://dev.kreatetechnologies.com/bee-ev/mobile',
    BASE_URL:'',
    BASE_URL_AUTH:'https://dev.kreatetechnologies.com/bee-ev/mobileauth/',
  
    GOOGLE_API_KEY:'AIzaSyB7sXDpmlCXzGXJOyOxfsr8gQUfv5PgDEk',
    COPYRIGHT_TEXT:'Copyright @ 2022, Bureau of Energy Efficiency | All rights reserved',
    TCO_URL:'',
    APP_LAT:0,
    APP_LONG:0,
    APP_LOCATION_TEXT:'',
    LOGIN_MOBILE_NUMBER:'',
    CHARGING_STATION_SEARCH_TEXT:'',
  
    USER_EMAIL:'',
    USER_NAME:'',
    GENDER:'',
    C_ID:'',
    S_ID:'',
    VEHICLE_TYPE:'',
    CHASSIS_NUMBER:'',
  
    EMAIL_LOGIN:'EMAIL_LOGIN',
    EMAIL_LOGIN_ERROR:'EMAIL_LOGIN_ERROR',
    EMAIL_LOGIN_SUCCESS:'EMAIL_LOGIN_SUCCESS',
  
    VALIDATE_EMIL_OTP:'VALIDATE_EMIL_OTP',
    VALIDATE_EMIL_OTP_DATA_SUCCESS:'VALIDATE_EMIL_OTP_DATA_SUCCESS',
    VALIDATE_EMAIL_OTP_DATA_ERROR:'VALIDATE_EMAIL_OTP_DATA_ERROR',
  
    ACCOUNT_DELETE:'ACCOUNT_DELETE',
    ACCOUNT_DELETE_ERROR:'ACCOUNT_DELETE_ERROR',
    ACCOUNT_DELETE_SUCCESS:'ACCOUNT_DELETE_SUCCESS',
  
    MAP_CHARGING_STATION_LIST_DATA:'MAP_CHARGING_STATION_LIST_DATA',
    MAP_CHARGING_STATION_LIST_DATA_ERROR:'MAP_CHARGING_STATION_LIST_DATA_ERROR',
    MAP_CHARGING_STATION_LIST_DATA_SUCCESS:'MAP_CHARGING_STATION_LIST_DATA_SUCCESS',
  
    JOURNEY_STATION_LIST_DATA:'JOURNEY_STATION_LIST_DATA',
    JOURNEY_STATION_LIST_DATA_ERROR:'JOURNEY_STATION_LIST_DATA_ERROR',
    JOURNEY_STATION_LIST_DATA_SUCCESS:'JOURNEY_STATION_LIST_DATA_SUCCESS',
  
    UPDATE_USER:'UPDATE_USER',
    UPDATE_USER_ERROR:'UPDATE_USER_ERROR',
    UPDATE_USER_SUCCESS:'UPDATE_USER_SUCCESS',
  
    PUBLIC_USER_EMAIL_VALIDATE_OTP_DATA:'PUBLIC_USER_EMAIL_VALIDATE_OTP_DATA',
    PUBLIC_USER_EMAIL_VALIDATE_OTP_DATA_ERROR:'PUBLIC_USER_EMAIL_VALIDATE_OTP_DATA_ERROR',
    PUBLIC_USER_EMAIL_VALIDATE_OTP_DATA_SUCCESS:'PUBLIC_USER_EMAIL_VALIDATE_OTP_DATA_SUCCESS',
  
  
    CHARGING_STATION_AC_DC_WISE_DATA:'CHARGING_STATION_AC_DC_WISE_DATA',
    CHARGING_STATION_AC_DC_WISE_ERROR:'CHARGING_STATION_AC_DC_WISE_ERROR',
    CHARGING_STATION_AC_DC_WISE_SUCCESS:'CHARGING_STATION_AC_DC_WISE_SUCCESS',
  
    FEEDBACK_DATA:'FEEDBACK_DATA',
    FEEDBACK_DATA_ERROR:'FEEDBACK_DATA_ERROR',
    FEEDBACK_DATA_SUCCESS:'FEEDBACK_DATA_SUCCESS',
    
  
    COUNTRY_DATA: 'COUNTRY_DATA',
    COUNTRY_DATA_ERROR: 'COUNTRY_DATA_ERROR',
    COUNTRY_DATA_SUCCESS: 'COUNTRY_DATA_SUCCESS',
  
    GENERATE_OTP_PUBLIC_DATA : 'GENERATE_OTP_PUBLIC_DATA',
    GENERATE_OTP_PUBLIC_DATA_ERROR : 'GENERATE_OTP_PUBLIC_DATA_ERROR',
    GENERATE_OTP_PUBLIC_DATA_SUCCESS : 'GENERATE_OTP_PUBLIC_DATA_SUCCESS',
  
    VALIDATE_OTP_DATA : 'VALIDATE_OTP_DATA',
    VALIDATE_OTP_DATA_ERROR : 'VALIDATE_OTP_DATA_ERROR',
    VALIDATE_OTP_DATA_SUCCESS : 'VALIDATE_OTP_DATA_SUCCESS',
  
    USER_REGISTRATION_DATA : 'USER_REGISTRATION_DATA',
    USER_REGISTRATION_DATA_ERROR : 'USER_REGISTRATION_DATA_ERROR',
    USER_REGISTRATION_DATA_SUCCESS : 'USER_REGISTRATION_DATA_SUCCESS',
  
    PUBLIC_USER_VALIDATE_OTP_DATA : 'PUBLIC_USER_VALIDATE_OTP_DATA',
    PUBLIC_USER_VALIDATE_OTP_DATA_ERROR : 'PUBLIC_USER_VALIDATE_OTP_DATA_ERROR',
    PUBLIC_USER_VALIDATE_OTP_DATA_SUCCESS : 'PUBLIC_USER_VALIDATE_OTP_DATA_SUCCESS',
  
    STATE_LIST_DATA : 'STATE_LIST_DATA',
    STATE_LIST_DATA_ERROR : 'STATE_LIST_DATA_ERROR',
    STATE_LIST_DATA_SUCCESS : 'STATE_LIST_DATA_SUCCESS',
  
    CITY_LIST_DATA : 'CITY_LIST_DATA',
    CITY_LIST_DATA_ERROR : 'CITY_LIST_DATA_ERROR',
    CITY_LIST_DATA_SUCCESS : 'CITY_LIST_DATA_SUCCESS',
    
    CHARGING_STATION_LIST_DATA : 'CHARGING_STATION_LIST_DATA',
    CHARGING_STATION_LIST_DATA_ERROR : 'CHARGING_STATION_LIST_DATA_ERROR',
    CHARGING_STATION_LIST_DATA_SUCCESS : 'CHARGING_STATION_LIST_DATA_SUCCESS',
  
    AVAILABLE_SLOT_DATA:'AVAILABLE_SLOT_DATA',
    AVAILABLE_SLOT_ERROR:'AVAILABLE_SLOT_ERROR',
    AVAILABLE_SLOT_SUCCESS:'AVAILABLE_SLOT_SUCCESS',
  
    BOOKING_SLOT_DATA:'BOOKING_SLOT_DATA',
    BOOKING_SLOT_ERROR:'BOOKING_SLOT_ERROR',
    BOOKING_SLOT_SUCCESS:'BOOKING_SLOT_SUCCESS',
  
    CHARGING_STATION_LIST_DATA2:'CHARGING_STATION_LIST_DATA2',
    CHARGING_STATION_LIST_DATA2_ERROR:'CHARGING_STATION_LIST_DATA2_ERROR',
    CHARGING_STATION_LIST_DATA2_SUCCESS:'CHARGING_STATION_LIST_DATA2_SUCCESS',
  
    FILTER_DATA:'FILTER_DATA',
    FILTER_DATA_ERROR:'FILTER_DATA_ERROR',
    FILTER_DATA_SUCCESS:'FILTER_DATA_SUCCESS',
  
    CHARGER_DATA:'CHARGER_DATA',
    CHARGER_DATA_ERROR:'CHARGER_DATA_ERROR',
    CHARGER_DATA_SUCCESS:'CHARGER_DATA_SUCCESS',
  
    VEHICLE_DATA:'VEHICLE_DATA',
    VEHICLE_DATA_ERROR:'VEHICLE_DATA_ERROR',
    VEHICLE_DATA_SUCCESS:'VEHICLE_DATA_SUCCESS',
  
    CHARGING_HISTORY_DATA : 'CHARGING_HISTORY_DATA',
    CHARGING_HISTORY_DATA_ERROR : 'CHARGING_HISTORY_DATA_ERROR',
    CHARGING_HISTORY_DATA_SUCCESS : 'CHARGING_HISTORY_DATA_SUCCESS',
  
    BOOKING_USER_DETAIL_DATA : 'BOOKING_USER_DETAIL_DATA',
    BOOKING_USER_DETAIL_ERROR : 'BOOKING_USER_DETAIL_ERROR',
    BOOKING_USER_DETAIL_SUCCESS : 'BOOKING_USER_DETAIL_SUCCESS',
  
    ADD_MY_VECHILE_DATA : 'ADD_MY_VECHILE_DATA',
    ADD_MY_VECHILE_ERROR : 'ADD_MY_VECHILE_ERROR',
    ADD_MY_VECHILE_SUCCESS : 'ADD_MY_VECHILE_SUCCESS',
    
    MY_VECHILE_DATA : 'MY_VECHILE_DATA',
    MY_VECHILE_ERROR : 'MY_VECHILE_ERROR',
    MY_VECHILE_SUCCESS : 'MY_VECHILE_SUCCESS',
  
    DELETE_MY_VECHILE_DATA : 'DELETE_MY_VECHILE_DATA',
    DELETE_MY_VECHILE_ERROR : 'DELETE_MY_VECHILE_ERROR',
    DELETE_MY_VECHILE_SUCCESS : 'DELETE_MY_VECHILE_SUCCESS',
  
    SAVE_STATION_DATA:'SAVE_STATION_DATA',
    SAVE_STATION_DATA_ERROR:'SAVE_STATION_DATA_ERROR',
    SAVE_STATION_DATA_SUCCESS:'SAVE_STATION_DATA_SUCCESS',
  
    GET_SAVED_STATION_LIST_DATA:'GET_SAVED_STATION_LIST_DATA',
    SAVED_STATION_LIST_DATA_ERROR:'SAVED_STATION_LIST_DATA_ERROR',
    SAVED_STATION_LIST_DATA_SUCCESS:'SAVED_STATION_LIST_DATA_SUCCESS',
  
    DELETE_SAVED_STATION_LIST:'DELETE_SAVED_STATION_LIST',
    DELETE_STATION_LIST_ERROR:'DELETE_STATION_LIST_ERROR',
    DELETE_STATION_LIST_SUCCESS:'DELETE_STATION_LIST_SUCCESS',
  
    ROUTE_STATIONS_LIST_DATA:'ROUTE_STATIONS_LIST_DATA',
    ROUTE_STATIONS_LIST_DATA_ERROR:'ROUTE_STATIONS_LIST_DATA_ERROR',
    ROUTE_STATIONS_LIST_DATA_SUCCESS:'ROUTE_STATIONS_LIST_DATA_SUCCESS',
  
    STATE_WISE_TARIFF_DATA:'STATE_WISE_TARIFF_DATA',
    STATE_WISE_TARIFF_DATA_ERROR:'STATE_WISE_TARIFF_DATA_ERROR',
    STATE_WISE_TARIFF_DATA_SUCCESS:'STATE_WISE_TARIFF_DATA_SUCCESS',
  
    EV_VEHICLE_MODEL_DATA:'EV_VEHICLE_MODEL_DATA',
    EV_VEHICLE_MODEL_DATA_ERROR:'EV_VEHICLE_MODEL_DATA_ERROR',
    EV_VEHICLE_MODEL_DATA_SUCCESS:'EV_VEHICLE_MODEL_DATA_SUCCESS',
  
    ICE_VEHICLE_MODEL_DATA:'ICE_VEHICLE_MODEL_DATA',
    ICE_VEHICLE_MODEL_DATA_ERROR:'ICE_VEHICLE_MODEL_DATA_ERROR',
    ICE_VEHICLE_MODEL_DATA_SUCCESS:'ICE_VEHICLE_MODEL_DATA_SUCCESS',
  
    EV_VEHICLE_DATA:'EV_VEHICLE_DATA',
    EV_VEHICLE_DATA_ERROR:'EV_VEHICLE_DATA_ERROR',
    EV_VEHICLE_DATA_SUCCESS:'EV_VEHICLE_DATA_SUCCESS',
  
    ICE_VEHICLE_DATA:'ICE_VEHICLE_DATA',
    ICE_VEHICLE_DATA_ERROR:'ICE_VEHICLE_DATA_ERROR',
    ICE_VEHICLE_DATA_SUCCESS:'ICE_VEHICLE_DATA_SUCCESS',
  
    CALCULATE_TCO_DATA:'CALCULATE_TCO_DATA',
    CALCULATE_TCO_DATA_ERROR:'CALCULATE_TCO_DATA_ERROR',
    CALCULATE_TCO_DATA_SUCCESS:'CALCULATE_TCO_DATA_SUCCESS',
  
  
  
    selectedLanguage:''
    
  
  };
  
  export { CONSTANT };