export const IMAGES =
{
    pickLocation: require('./pickLocation.png'),
    swapIcon: require('./swapIcon.png'),
    thumpsUp:require('./thumpsUp.png'),
    qrImage:require('./qrImage.png'),
    shareIcon:require('./shareIcon.png'),
    chargingStation:require('./chargingStation.png'),
    checkTime:require('./checkTime.png'),
    distanceMarker:require('./distanceMarker.png'),
    backArrow:require('./backArrow.png'),
    downArrow:require('./down_arrow.png'),
    scooter:require('./scooter.png'),
    auto:require('./auto.png'),
    car:require('./car.png'),
    calander:require('./calander.png'),
    direction:require('./direction.png'),
    rightIcon:require('./rightIcon.png'),
    wrong:require('./wrong.png'),
    faqThinking:require('./faqThinking.png'),
    search:require('./search.png'),
    uparrow:require('./uparrow.png'),
    down:require('./down.png'),
    hyundai:require('./hyundai.jpg'),
    delete:require('./delete.png'),
    login:require('./login12.jpg'),
    ac1:require('./ac1.png'),
    ac2:require('./ac2.png'),
    dc1:require('./dc1.png'),
    dc2:require('./dc2.png'),
    chademo:require('./chademo.png'),
    akam:require('./akam.png'),
    drink:require('./drink.png'),
    firstAid:require('./firstaid.png'),
    call:require('./call.png'),
    person:require('./person.png'),
    location:require('./location.png'),
    freeParking:require('./freeParking.png'),
    login1:require('./login1.png'),

    salon:require('./salon.png'),
    medical:require('./medical.png'),
    park:require('./park.png'),
    autoService:require('./autoService.png'),
    rupee:require('./rupee.png'),
    chargerMap:require('./chargerMap.png'),
    chat:require('./chat.png'),
    connectors:require('./connectors.png'),
    clock:require('./clock.png'),
    evcharger:require('./evcharger.png'),
    bookmark:require('./bookmark.png'),
    bookmark1:require('./bookmark1.png'),

    pin1:require('./pin1.png'),
    pin2:require('./pin2.png'),
    pin3:require('./pin3.png'),
    pin4:require('./pin4.png'),
    selected:require('./selected.png'),
    loader:require('./loader.gif'),
    bukmark:require('./bukmark.png'),
    shop:require('./shop.png'),
    restaurant:require('./restaurant.png'),
    firstaid:require('./firstaid.png'),
    rest:require('./rest.png'),
    uparrow1:require('./uparrow1.png'),
    pin3:require('./pin3.png'),
    closeInCircel:require('./closeInCircel.png'),
    company:require('./company.png'),
    rightArrow:require('./rightArrow.png'),
    scrnsht:require('./scrnsht.jpeg'),
    goElectric:require('./goElectric.png'),
    back:require('./back.jpg'),
    loginLogo:require('./loginLogo.png'),
    availableCharger:require('./availableCharger.png'),
    direction_Arrow:require('./direction_Arrow.png'),
    isSaved:require('./isSaved.png'),
    notAvailable:require('./notAvailable.png'),
    notSaved:require('./notSaved.png'),
    phoneCall:require('./phoneCall.png'),
    calling:require('./calling.png'),
    dir1:require('./dir1.png'),
    dir2:require('./dir2.png'),
    dir4:require('./dir4.png'),
    buk1:require('./buk1.png'),
    buk2:require('./buk2.png'),
    remove:require('./remove.png'),
    correct:require('./correct.png'),
    info:require('./info.png'),
    icon_charging:require('./icon_charging.png'),
    battery:require('./battery.png'),

    english:require('./eng.png'),
    hindi:require('./hindi.png'),
    english1:require('./eng1.png'),
    hindi1:require('./hindi1.png'),


    hexagon:require('./hexagon.png'),
    vehicle:require('./Vehicle.png'),
    user_guide:require('./user_guide.png'),
    add:require('./add.png'),
    deletebtn:require('./deletebtn.png'),
    g20:require('./g20.png'),


    tv:require('./tv.png'),
    forward:require('./forward.png'),

    news:require('./news.png'),


    

}